    <main class="container-xl">

        <p class="text-right mb-5 lead">Bienvenue, <?= htmlspecialchars($_SESSION['admin']['name']) ?></p>
        <h1 class="ml-5 ml-md-auto text-left">Modification du contenu de la page d'accueil</h1>

        <form action='' method='POST'>
            <div class="form-row">
                <div class="form-group col-md-6">
                <label for="title">Titre</label>
                <input type="text" class="form-control" id="title" value='<?= htmlspecialchars($content['title']) ?>' name="title">
                </div>
            </div>

            <div class="form-group">
                <label for="content">Contenu</label>
                <textarea class="form-control" id="content" rows="10" name="content"><?= htmlspecialchars($content['content']) ?></textarea>
            </div>

            <input type="hidden" name="id" value="<?= htmlspecialchars($content['id']) ?>">

            <button type="submit" class="btn btn-primary">Modifier</button>
        </form>

    </main>

</body>
</html>